### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sSokkaa**

### CODE REVIEW

**Review by Vexile — CHANGES_REQUESTED** [review]
Poorly done, please correct EVERYTHING.

**Comment by sSokkaa** [comment]
I will not

**Comment by sSokkaa** [comment]
plz

**Comment by sSokkaa** [comment]
plz

**Review by Vexile — APPROVED** [review]
Bravo!

**Comment by sSokkaa** [comment]
HA

**Comment by sSokkaa** [comment]
Virus injected

**Pull request merged**
